name: Expo Publish
on:
  push:
    branches: 
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
            node-version: 12.x
      - uses: expo/expo-github-action@v5
        with:
            expo-username: ${{ secrets.EXPO_CLI_USERNAME }}
            expo-password: ${{ secrets.EXPO_CLI_PASSWORD }}
            expo-cache: true
      - run: yarn install
      - run: expo publish
        env:
          EXPO_DEBUG: true
