name: CI Build
on:
  push:
    branches:
      - master
jobs:
  publish:
    name: Install and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: expo/expo-github-action@v5
        with:
          expo-version: 3.13.1
          expo-username: ${{ secrets.EXPO_USERNAME }}
          expo-password: ${{ secrets.EXPO_PASSWORD }}
      - run: echo 'Running NPM Install'
      - run: npm ci
      - run: npm run test
      - run: expo publish --non-interactive
        if: github.ref == 'refs/heads/master'
        env:
         EXPO_DEBUG: true
